spring.application.name=exam-jee

spring.datasource.url=jdbc:h2:mem:exam-db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8086
spring.jpa.show-sql=true


jwt.secret=9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338